
export enum ACCOUNT_TYPES {
  CHECKING = "CHECKING",
  SAVINGS = "SAVINGS",
  CREDITCARD="CREDITCARD",
  LOAN="LOAN",
  KIWISAVER="KIWISAVER",
  INVESTMENT="INVESTMENT",
  TERMDEPOSIT="TERMDEPOSIT",
  FOREIGN="FOREIGN",
  TAX="TAX",
  REWARDS="REWARDS",
  WALLET="WALLET",
}